FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

ENV FLASK_APP=app.py
ENV CLIENT_ID="Iv23liD66WZlyxG5kvkr"
ENV CLIENT_SECRET="199bfdce8f54a57382efc67e93a63378f1900d17"

CMD ["flask", "run", "--host=0.0.0.0"]
